# Generated by Django 3.1.7 on 2021-03-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDeatails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Start_Time', models.TimeField(auto_now_add=True)),
                ('End_Time', models.TimeField(auto_now_add=True)),
                ('Creation_Timestamp', models.CharField(max_length=30)),
            ],
        ),
    ]
