# Generated by Django 3.1.7 on 2021-03-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting_Schedule_App', '0005_auto_20210305_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingDetails',
            new_name='MeetingDeatails',
        ),
    ]
