# Generated by Django 3.1.7 on 2021-03-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting_Schedule_App', '0006_auto_20210305_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingDeatails',
        ),
    ]
