# Generated by Django 3.1.7 on 2021-03-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting_Schedule_App', '0008_meetingdeatails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingDeatails',
        ),
    ]
