# Generated by Django 3.1.7 on 2021-03-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting_Schedule_App', '0016_participantdetails_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdetails',
            name='End_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meetingdetails',
            name='Start_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
