# Generated by Django 3.1.7 on 2021-03-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting_Schedule_App', '0017_auto_20210306_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdetails',
            name='Creation_Timestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingdetails',
            name='End_Time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingdetails',
            name='Start_Time',
            field=models.DateTimeField(blank=True),
        ),
    ]
