# Generated by Django 3.1.7 on 2021-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting_Schedule_App', '0018_auto_20210307_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdetails',
            name='Creation_Timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
